{
 "title": "Enedis Teleinfo",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "tarif_hp", "query": "0.11653" },
   { "name": "tarif_hc", "query": "0.09172" },
   {
    "name": "consommation_hp",
    "query": "\tSELECT (a.max_index_hp - a.min_index_hp) conso\n\tFROM \n\t(SELECT\n  \tmax(index_hp) AS \"max_index_hp\",\n  \tmin(index_hp) AS \"min_index_hp\"\n\tFROM consumption\n\tWHERE $__timeFilter(datetime)\n\t) a"
   },
   {
    "name": "consommation_hc",
    "query": "\tSELECT (a.max_index_hc - a.min_index_hc) conso\n\tFROM \n\t(SELECT\n  \tmax(index_hc) AS \"max_index_hc\",\n  \tmin(index_hc) AS \"min_index_hc\"\n\tFROM consumption\n\tWHERE $__timeFilter(datetime)\n\t) a"
   },
   { "name": "max_kva", "query": "6" },
   { "name": "tension", "query": "237" }
  ]
 },
 "panels": [
  {
   "title": "Index HP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "watth",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  index_hp AS \"Index HP\"\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Consommation HP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT ${consommation_hp}" }
   ]
  },
  {
   "title": "Consommation totale",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "watth",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT ${consommation_hp} + ${consommation_hc}"
    }
   ]
  },
  {
   "title": "Puissance instannée maximum",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  puissance_apparente\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Période",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  periode\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Indexs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  avg(index_hc) AS \"index HC\",\n  avg(index_hp) AS \"index HP\"\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nGROUP BY 1\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Index HC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "watth",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  index_hc AS \"index_hc\"\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Consommation HC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT ${consommation_hc}" }
   ]
  },
  {
   "title": "Prix de la consommation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "currencyEUR",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT (consommation_hc.conso/1000) * ${tarif_hc} + (consommation_hp.conso/1000) * ${tarif_hp} FROM\n\t(SELECT (a.max_index_hc - a.min_index_hc) conso\n\tFROM \n\t(SELECT\n  \tmax(index_hc) AS \"max_index_hc\",\n  \tmin(index_hc) AS \"min_index_hc\"\n\tFROM consumption\n\tWHERE $__timeFilter(datetime)) a) consommation_hc, \n    (SELECT (b.max_index_hp - b.min_index_hp) conso\n\tFROM \n\t(SELECT\n  \tmax(index_hp) AS \"max_index_hp\",\n  \tmin(index_hp) AS \"min_index_hp\"\n\tFROM consumption\n\tWHERE $__timeFilter(datetime)) b) consommation_hp"
    }
   ]
  },
  {
   "title": "Puissance ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "voltamp", "label": "Puissance apparente" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  avg(puissance_apparente) AS \"Puissance apparente\",\n  (avg(intensite_inst) * ${tension}) AS \"Puissance active\"\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nGROUP BY 1\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Intensité",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "amp", "label": "Intensité" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  avg(intensite_inst) AS \"Intensité\"\nFROM consumption\nWHERE\n  $__timeFilter(datetime)\nGROUP BY 1\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  }
 ]
}